# Generated by Django 4.2.1 on 2023-05-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_hiring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiring',
            old_name='id_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='hiring',
            old_name='id_employer',
            new_name='employer',
        ),
    ]
