# Generated by Django 4.2.1 on 2023-05-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_hiring_date_of_dismissal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiring',
            old_name='data_of_employment',
            new_name='date_of_employment',
        ),
    ]
